class Jugador 
class Juego
class CircusCharlie 
    class Nivel1
    class Nivel2
    class Nivel3
    class Nivel4
    class Nivel5
    class Payaso 
    class EscenarioAroDeFuego
    class Obstaculo
    class Mono
    class EscenarioEquilibrio
    class EscenarioPelota
    class EscenarioRebote  
    class EscenarioLiana   
    class Liana 
    class Caballo    
    class Animal
    class Leon 
    class AroDeFuego
    class Caldera 
    class Publico 
    class Sonido
    class Puntaje
    class Vida 
    class Bonu
    class Distancia
    class AroDeFuegoConDinero
    class Podio 
    class Elefante 
    class AroDeFuegoConDinero
    class PuntoPorNivel
    class PuntoExtra
    class LigaDeEquilibrio 
    class MonoAzul
    class Persona  
    class Pelota 
    Class Brincolin 
    class Objeto 
    class Trampolin 
    class Tiempo 
    class Meta 
    class Menu 
    class Inicio 

    Distancia--|>Tiempo 
    Payaso--|>Persona 
    MonoAzul--|>Animal 
    Caballo--|>Animal
    Juego*--Payaso 
    Payaso o--Caballo 
    Mono--|>Animal
    Juego*--Jugador
    Leon--|>Animal 
    Leon o--AroDeFuego
    CircusCharlie--|>Juego
    Distancia--|>Objeto 
    Jugador o--CircusCharlie
    Jugador o--Persona 
    Jugador o--Juego 
    Jugador o--Nivel1
    Jugador o--Nivel2
    Jugador o--Nivel3
    Jugador o--Nivel4
    Jugador o--Nivel5
    Jugador o--Vida 
    Jugador o--Inicio
    Jugador o--Menu
    LigaDeEquilibrio--|>Objeto 
    Podio--|>Objeto 
    Publico--|>Objeto 
    Obstaculo--|>Objeto 
    AroDeFuego--|>Obstaculo
    AroDeFuegoConDinero--|>Obstaculo 
    Mono--|>Obstaculo
    MonoAzul--|>Obstaculo 
    Pelota--|>Obstaculo 
    Brincolin--|>Obstaculo 
    Liana--|>Obstaculo 
    Trampolin--|>Obstaculo 
    Nivel1--|>EscenarioAroDeFuego
    Nivel2--|>EscenarioEquilibrio
    Nivel3--|>EscenarioPelota
    Nivel4--|>EscenarioRebote 
    Nivel5--|>EscenarioLiana 
    Podio--|>Meta 
    Juego*--EscenarioAroDeFuego
    Juego*--EscenarioEquilibrio
    Juego*--EscenarioPelota
    Juego*--EscenarioRebote
    Juego*--EscenarioLiana 
    Juego*--Nivel1
    Juego*--Nivel2
    Juego*--Nivel3
    Juego*--Nivel4
    Juego*--Nivel5
    Nivel1*--Payaso
    Nivel1*--EscenarioAroDeFuego
    Nivel1*--Leon
    Nivel1*--AroDeFuego
    Nivel1*--Caldera
    Nivel1*--Publico
    Nivel1*--Sonido
    Nivel1*--Vida
    Nivel1*--Elefante
    Nivel1*--Bonu
    Nivel1*--Distancia
    Nivel1*--AroDeFuegoConDinero 
    Nivel1*--Puntaje 
    Nivel1*--Distancia 
    Leon o--AroDeFuegoConDinero
    Payaso o--AroDeFuegoConDinero
    Payaso o--AroDeFuego
    Nivel2*--EscenarioEquilibrio
    Nivel2*--LigaDeEquilibrio
    Nivel2*--Mono
    Nivel2*--Payaso
    Nivel2*--MonoAzul 
    Nivel2*--Vida 
    Nivel2*--Podio 
    Nivel2*--Sonido
    Nivel2*--Publico
    Nivel2*--PuntoExtra 
    Nivel2*--Puntaje 
    Nivel2*--LigaDeEquilibrio
    Nivel2*--Distancia 
    Payaso o--Mono
    Payaso o--MonoAzul 
    Payaso o--LigaDeEquilibrio 
    Payaso o--Brincolin 
    Payaso o--Podio 
    Payaso o--Liana 
    Payaso o--Trapolin 
    Payaso o--PuntoPorNivel
    Payaso o--PuntoExtra 
    Payaso*--Vida 
    Nivel3*--Payaso 
    Nivel3*--Pelota 
    Nivel3*--EscenarioPelota 
    Nivel3*--Podio
    Nivel3*--Vida 
    Nivel3*--Bonu 
    Nivel3*--Sonido 
    Nivel3*--Pelota 
    Nivel3*--Publico 
    Nivel3*--Distancia 
    Nivel3*--Puntaje 
    Nivel3*--PuntoExtra
    Nivel4*--Payaso
    Nivel4*--Brincolin 
    Nivel4*--Caballo 
    Nivel4*--Vida 
    Nivel4*--EscenarioRebote 
    Nivel4*--Sonido 
    Nivel4*--Distancia
    Nivel4*--Podio 
    Nivel4*--Puntaje  
    Nivel4*--PuntoExtra
    Nivel4*--Publico 
    Nivel5*--Vida
    Nivel5*--Sonido 
    Nivel5*--Payaso 
    Nivel5*--Liana 
    Nivel5*--Trampolin
    Nivel5*--Distancia 
    Nivel5*--Podio 
    Nivel5*--Puntaje 
    Nivel5*--Publico 
    Inicio*--Menu 
    Juego*--Inicio
    Juego*--Menu






